TARGET=autopilot
CC=g++
INCLUDE=-I/home/noth/dev/ARDrone/ARDrone_SDK_1_5_Version_20101004/ARDroneLib/VP_SDK/VP_Os/linux/ \
        -I/home/noth/dev/ARDrone/ARDrone_SDK_1_5_Version_20101004/ARDroneLib/VP_SDK/ \
        -I/home/noth/dev/ARDrone/ARDrone_SDK_1_5_Version_20101004/ARDroneLib/Soft/Lib/ \
        -I/home/noth/dev/ARDrone/ARDrone_SDK_1_5_Version_20101004/ARDroneLib/Soft/Common/ \
        -I/home/noth/dev/ARDrone/ARDrone_SDK_1_5_Version_20101004/ARDroneLib/ \
        -I./external/revel-1.1.0/include/ \
        -I./

LIBDIR=-L/home/noth/dev/ARDrone/ARDrone_SDK_1_5_Version_20101004/ARDroneLib/Soft/Build/targets_versions/ardrone_lib_PROD_MODE_vlib_Linux_2.6.29-1-netbook_GNU_Linux_gcc_4.3.3/ \
       -L/home/noth/dev/ARDrone/ARDrone_SDK_1_5_Version_20101004/ARDroneLib/Soft/Build/targets_versions/vlib_PROD_MODE_Linux_2.6.29-1-netbook_GNU_Linux_gcc_4.3.3/ \
       -L/home/noth/dev/ARDrone/ARDrone_SDK_1_5_Version_20101004/ARDroneLib/Soft/Build/targets_versions/sdk_PROD_MODE_vlib_Linux_2.6.29-1-netbook_GNU_Linux_gcc_4.3.3/\
       -L./external/revel-1.1.0/lib/


LIBS=-lpc_ardrone -lvlib -lrt -lsdk -lSDL -lSDL_ttf  -lSDL_gfx -lrevel -lxvidcore -g
CFLAGS=-g -Wall  -DUSE_LINUX

SOURCES = ardroneLink.cpp \
          ardroneVideo.cpp \
          ardroneIhm.cpp \
          dataCentral.cpp \
          SDLFlightRollPitch.cpp \
          SDLFlightYawAlt.cpp \
          SDLFlightFuel.cpp \
          BlackBox.cpp \
          ControlLayer.cpp

OBJ= $(SOURCES:.cpp=.o)

%.o: %.cpp
	$(CC) -o $@ -c $< $(CFLAGS) $(INCLUDE)

all: $(OBJ)
	$(CC) *.o  $(LIBDIR) $(LIBS)  -o $(TARGET)

clean:
	rm *.o
